language: elixir
elixir:
  - '1.8.1'
otp_release:
  - '21.3'
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.1
script:
  - bash scripts/travis.sh
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh master
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh release
  on:
    tags: true
branches:
  only:
  - master
  - /\d{1,3}\.\d{1,3}\.\d{1,3}/
