language: elixir
elixir:
  - '1.8.1'
otp_release:
  - '21.3'
services:
  - docker
jobs:
  include:
    - name: verify
      script: bash scripts/travis-verify.sh
    - name: unit test
      script: mix test
    - name: pipeline
      script: bash scripts/travis-test.sh pipeline
    - name: dead_letter
      script: bash scripts/travis-test.sh dead_letter
    - name: andi
      script: bash scripts/travis-test.sh andi
    - name: flair
      script: bash scripts/travis-test.sh flair
    - name: forklift
      script: bash scripts/travis-test.sh forklift
    - name: e2e
      script: bash scripts/travis-test.sh e2e
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-publish.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/travis-publish.sh
    on:
      tags: true
branches:
  only:
  - master
  - /(andi|forklift|flair):\d{1,3}\.\d{1,3}\.\d{1,3}/
