apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: clusterlib
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            memory: 512Mi
            cpu: 100m
          requests:
            memory: 512Mi
            cpu: 100m
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}
        - configMapRef:
            name: kafka-brokers
        env:
        - name: RUN_IN_KUBERNETES
          value: "true"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
