apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterlib
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: clusterlib
rules:
  - apiGroups: [""]
    resources:
      - endpoints
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: clusterlib-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterlib
subjects:
- kind: ServiceAccount
  name: clusterlib
  namespace: cota-services
