replicaCount: 2

image:
  repository: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/forklift
  tag: latest
  pullPolicy: IfNotPresent

monitoring:
  targetPort: 4000
# If running locally on Minikube, set to true to deploy an AWS localstack instance
# https://github.com/localstack/localstack
localstack:
  enabled: false

kafka:
  #comma delimited list of kafka seed brokers
  brokers: "forklift-kafka-bootstrap.forklift-prime:9092"
  strimziCluster: forklift # http://strimzi.io/docs/0.4.0/#_topic_configmap

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

presto:
  url:
