---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
  kafka:
    image: confluentinc/cp-kafka:4.1.0
    ports:
      - 9092:9092
      - 9093:9093
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: CLUSTER://kafka:9093,LOCAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CLUSTER:PLAINTEXT,LOCAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CLUSTER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"
  aws:
    image: localstack/localstack:0.8.7
    environment:
      SERVICES: "cloudwatch"
    ports:
      - 4582:4582
      - 8080:8080
  producer:
    build:
      context: .
    image: producer
    depends_on:
      - kafka
      - aws
    ports:
      - 4000:4000
    environment:
      KAFKA_BROKERS: "kafka:9093"
