---
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "dataset-registry:1:1,streaming-transformed:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  aws:
    image: localstack/localstack:0.8.7
    environment:
      SERVICES: "cloudwatch"
    ports:
      - 4582:4582
      - 8080:8080
  # producer:
  #   build:
  #     context: .
  #   image: producer
  #   depends_on:
  #     - kafka
  #     - aws
  #   ports:
  #     - 4000:4000
  #   environment:
  #     KAFKA_BROKERS: "kafka:9093"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
