apiVersion: v1
kind: Service
metadata:
  name: cota-streaming-consumer
spec:
  selector:
    app: cota-streaming-consumer
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
    nodePort: 30070
  type: NodePort
